"""add analysis_source to messages

Revision ID: 2e3a7f4d4c99
Revises: a349eeeedfdc
Create Date: 2026-07-27 20:51:48.642991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e3a7f4d4c99'
down_revision: Union[str, None] = 'a349eeeedfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('analysis_source', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'analysis_source')
    # ### end Alembic commands ###
