"""add analysis columns to messages

Revision ID: a349eeeedfdc
Revises: 791b3d7bb79e
Create Date: 2026-07-27 19:33:30.242733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a349eeeedfdc'
down_revision: Union[str, None] = '791b3d7bb79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Not autogenerated: under asyncpg, add_column does not emit CREATE TYPE, so
    # the ALTER TABLE fails with 'type "analysis_status" does not exist'. Create
    # the enum explicitly first.
    analysis_status = sa.Enum('pending', 'complete', 'failed', name='analysis_status')
    analysis_status.create(op.get_bind(), checkfirst=True)
    op.add_column('messages', sa.Column('analysis_status', analysis_status, server_default='pending', nullable=False))
    op.add_column('messages', sa.Column('mood', sa.String(length=32), nullable=True))
    op.add_column('messages', sa.Column('toxicity_score', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('heat_score', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('rewrite_suggestion', sa.Text(), nullable=True))
    op.create_index(op.f('ix_messages_analysis_status'), 'messages', ['analysis_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_analysis_status'), table_name='messages')
    op.drop_column('messages', 'rewrite_suggestion')
    op.drop_column('messages', 'heat_score')
    op.drop_column('messages', 'toxicity_score')
    op.drop_column('messages', 'mood')
    op.drop_column('messages', 'analysis_status')
    # ### end Alembic commands ###
    # Not autogenerated: add_column creates the enum type, but drop_column does
    # not remove it. Without this, re-running the upgrade fails with
    # "type analysis_status already exists".
    sa.Enum(name='analysis_status').drop(op.get_bind(), checkfirst=True)
